filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /opt/tpot/logs/**/*.log
  fields:
    logtype: honeypot
  fields_under_root: true
  multiline.pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
  multiline.negate: true
  multiline.match: after
  scan_frequency: 10s
  harvester_buffer_size: 16384
  max_bytes: 10485760

- type: log
  enabled: true
  paths:
    - /opt/tpot/logs/cowrie.log
  fields:
    honeypot: cowrie
    logtype: cowrie
  fields_under_root: true
  json.keys_under_root: true
  json.add_error_key: true

- type: log
  enabled: true
  paths:
    - /opt/tpot/logs/dionaea.log
  fields:
    honeypot: dionaea
    logtype: dionaea
  fields_under_root: true
  json.keys_under_root: true
  json.add_error_key: true

- type: log
  enabled: true
  paths:
    - /opt/tpot/logs/honeytrap.log
  fields:
    honeypot: honeytrap
    logtype: honeytrap
  fields_under_root: true
  json.keys_under_root: true
  json.add_error_key: true

- type: docker
  enabled: true
  containers.ids:
    - '*'
  containers.stream: stdout
  containers.stream: stderr

output.logstash:
  hosts: ["logstash:5044"]
  compression_level: 3
  worker: 2

logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644

processors:
- add_host_metadata:
    when.not.contains.tags: forwarded

- add_docker_metadata:
    host: "unix:///var/run/docker.sock"

- drop_event:
    when:
      regexp:
        message: '^#'

setup.template.settings:
  index.number_of_shards: 1
  index.number_of_replicas: 0
