name: Build & Test Installation

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  full-install-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    
    - name: Install all dependencies (CRITICAL)
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install -e ".[dev]"
        echo "✅ Все зависимости установлены"
        
        # Проверяем что ключевые зависимости установлены
        python -c "import ijson; print('✅ ijson установлен')"
        python -c "import aiohttp; print('✅ aiohttp установлен')"
        python -c "import click; print('✅ click установлен')"
    
    - name: Check Python syntax (CRITICAL)
      run: |
        echo "🔍 Проверяем синтаксис Python файлов..."
        python -m py_compile src/llmstruct/*.py
        echo "✅ Синтаксис корректен"
    
    - name: Check critical lint errors (CRITICAL)
      run: |
        echo "🔍 Проверяем критические ошибки..."
        flake8 src/llmstruct --select=E9,F63,F7,F82 --show-source --statistics
        echo "✅ Критических ошибок нет"
    
    - name: Test full package import (CRITICAL)
      run: |
        echo "🔍 Проверяем импорт всех модулей..."
        python -c "
        import llmstruct
        print('✅ Основной пакет импортируется')
        
        # Пробуем импортировать основные модули
        try:
            from llmstruct.cli import main
            print('✅ CLI модуль импортируется')
        except Exception as e:
            print(f'❌ CLI модуль: {e}')
            exit(1)
        
        try:
            from llmstruct.llm_client import LLMClient
            print('✅ LLM Client импортируется')
        except Exception as e:
            print(f'⚠️ LLM Client: {e}')
        
        print('✅ Импорт пакета завершен')
        "
    
    - name: Test CLI help command (CRITICAL)
      run: |
        echo "🔍 Проверяем работу CLI..."
        python -m llmstruct --help
        echo "✅ CLI работает"
    
    - name: Test CLI basic commands (NON-CRITICAL)
      run: |
        echo "🔍 Проверяем основные команды CLI..."
        # Создаем директорию для логов
        mkdir -p ci-logs
        # Тестируем parse на самом проекте
        echo "=== CLI Parse Test ===" > ci-logs/cli-test.log
        python -m llmstruct parse . -o test_output.json 2>&1 | tee -a ci-logs/cli-test.log || {
          echo "⚠️ Parse команда не сработала, но это некритично" | tee -a ci-logs/cli-test.log
          echo "FAILED" > ci-logs/cli-status.txt
          exit 0
        }
        if [ -f "test_output.json" ]; then
            echo "✅ Parse команда создала файл" | tee -a ci-logs/cli-test.log
            ls -la test_output.json | tee -a ci-logs/cli-test.log
            echo "SUCCESS" > ci-logs/cli-status.txt
        else
            echo "⚠️ Parse команда не создала файл, но продолжаем" | tee -a ci-logs/cli-test.log
            echo "PARTIAL" > ci-logs/cli-status.txt
        fi
        echo "✅ Тестирование CLI завершено" | tee -a ci-logs/cli-test.log

    - name: Validate test_output.json (CRITICAL)
      run: |
        if [ -f "test_output.json" ]; then
          echo "🔍 Проверяем валидность test_output.json..."
          python -c "import json; json.load(open('test_output.json'))" && \
            echo "✅ test_output.json валиден" || \
            (echo "❌ test_output.json НЕвалиден" && exit 1)
        else
          echo "❌ test_output.json не найден, не могу проверить валидность"
          exit 1
        fi
    
    - name: Check style warnings (NON-CRITICAL)
      run: |
        echo "🔍 Проверяем стиль кода (некритично)..."
        
        # Создаем лог файл для стиля
        echo "=== Style Check ===" > ci-logs/style-check.log
        flake8 src/llmstruct --max-line-length=88 --statistics 2>&1 | tee -a ci-logs/style-check.log || {
          echo "⚠️ Есть предупреждения по стилю, но это некритично" | tee -a ci-logs/style-check.log
          echo "WARNINGS" > ci-logs/style-status.txt
          exit 0
        }
        echo "SUCCESS" > ci-logs/style-status.txt
        echo "✅ Проверка стиля завершена" | tee -a ci-logs/style-check.log
    
    - name: Final validation (CRITICAL)
      run: |
        echo "🎯 Финальная проверка установки..."
        python -c "
        import sys
        import llmstruct
        
        print(f'Python version: {sys.version}')
        
        if hasattr(llmstruct, '__version__'):
            print(f'LLMStruct version: {llmstruct.__version__}')
        else:
            print('LLMStruct version: не определена')
        
        print('✅ Проект полностью рабочий!')
        " 
    
    - name: Write job summary
      if: always()
      run: |
        echo "## 📊 Краткий отчет по CI" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### 🧪 Выполненные тесты" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        if [ -f "ci-logs/cli-status.txt" ]; then
          CLI_STATUS=$(cat ci-logs/cli-status.txt)
          echo "- 🔧 CLI тесты: $CLI_STATUS" >> $GITHUB_STEP_SUMMARY
        else
          echo "- 🔧 CLI тесты: НЕ ЗАПУСКАЛИСЬ" >> $GITHUB_STEP_SUMMARY
        fi
        if [ -f "ci-logs/style-status.txt" ]; then
          STYLE_STATUS=$(cat ci-logs/style-status.txt)
          echo "- 🎨 Проверка стиля: $STYLE_STATUS" >> $GITHUB_STEP_SUMMARY
        else
          echo "- 🎨 Проверка стиля: НЕ ЗАПУСКАЛАСЬ" >> $GITHUB_STEP_SUMMARY
        fi
        if [ -f "test_output.json" ]; then
          python -c "import json; json.load(open('test_output.json'))" && \
            echo '- 🗂️ test_output.json: ВАЛИДЕН' >> $GITHUB_STEP_SUMMARY || \
            echo '- 🗂️ test_output.json: НЕВАЛИДЕН' >> $GITHUB_STEP_SUMMARY
        else
          echo '- 🗂️ test_output.json: НЕ СОЗДАН' >> $GITHUB_STEP_SUMMARY
        fi
        echo '' >> $GITHUB_STEP_SUMMARY
        echo '📁 Полные логи доступны в Artifacts.' >> $GITHUB_STEP_SUMMARY

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()  # Всегда выполняется, даже если что-то упало
      with:
        name: ci-test-results
        path: |
          ci-logs/
          test_output.json
        retention-days: 30
    
    # Показываем краткий отчет
    - name: Summary of non-critical tests
      if: always()
      run: |
        echo "📊 Краткий отчет по некритичным тестам:"
        echo "=================================="
        
        if [ -f "ci-logs/cli-status.txt" ]; then
          CLI_STATUS=$(cat ci-logs/cli-status.txt)
          echo "🔧 CLI тесты: $CLI_STATUS"
        else
          echo "🔧 CLI тесты: НЕ ЗАПУСКАЛИСЬ"
        fi
        
        if [ -f "ci-logs/style-status.txt" ]; then
          STYLE_STATUS=$(cat ci-logs/style-status.txt)
          echo "🎨 Проверка стиля: $STYLE_STATUS"
        else
          echo "🎨 Проверка стиля: НЕ ЗАПУСКАЛАСЬ"
        fi
        
        echo "=================================="
        echo "📁 Полные логи доступны в Artifacts" 